export class Receptes {
    id: number;
    name: String;
    description: String;
    ingredients: String;
}

export const RECEPTES: Receptes [] = [{id:1,name:"Almendras",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula nulla vitae sodales sodales. Curabitur ut magna consectetur, sollicitudin leo vel, malesuada leo. Etiam interdum velit at nisi ornare, nec convallis augue consequat. Phasellus gravida at eros efficitur dapibus. Nullam ut vestibulum libero. Praesent ac ornare risus, et cursus urna. Vestibulum eget condimentum augue. Donec posuere tempor elit vel posuere. Nam facilisis porttitor leo et fringilla. Duis odio velit, ultricies et tincidunt in, porta sed purus. Curabitur volutpat, nibh in molestie ultrices, arcu massa lacinia metus, in pellentesque urna est ut magna. Aenean non lorem sit amet purus placerat porta id nec urna. Curabitur vitae lorem mi.",ingredients:"e panela,50 g  de mantega,40 g oli de gira-sol,5 g de llevat,2  pomes Golden,2 pomes Granny Smith,2 cullerades de canyella en pols,2 canonets de canyella,cava,sal"},
                                      {id:2,name:"Pastís de poma",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula nulla vitae sodales sodales. Curabitur ut magna consectetur, sollicitudin leo vel, malesuada leo. Etiam interdum velit at nisi ornare, nec convallis augue consequat. Phasellus gravida at eros efficitur dapibus. Nullam ut vestibulum libero. Praesent ac ornare risus, et cursus urna. Vestibulum eget condimentum augue. Donec posuere tempor elit vel posuere. Nam facilisis porttitor leo et fringilla. Duis odio velit, ultricies et tincidunt in, porta sed purus. Curabitur volutpat, nibh in molestie ultrices, arcu massa lacinia metus, in pellentesque urna est ut magna. Aenean non lorem sit amet purus placerat porta id nec urna. Curabitur vitae lorem mi.",ingredients:"4 ous,150 g farina,180 g de sucre panela,50 g  de mantega,40 g oli de gira-sol,5 g de llevat,2  pomes Golden,2 pomes Granny Smith,2 cullerades de canyella en pols,2 canonets de canyella,cava,sal"},
                                      {id:3,name:"Estofat rebossat",description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula nulla vitae sodales sodales. Curabitur ut magna consectetur, sollicitudin leo vel, malesuada leo. Etiam interdum velit at nisi ornare, nec convallis augue consequat. Phasellus gravida at eros efficitur dapibus. Nullam ut vestibulum libero. Praesent ac ornare risus, et cursus urna. Vestibulum eget condimentum augue. Donec posuere tempor elit vel posuere. Nam facilisis porttitor leo et fringilla. Duis odio velit, ultricies et tincidunt in, porta sed purus. Curabitur volutpat, nibh in molestie ultrices, arcu massa lacinia metus, in pellentesque urna est ut magna. Aenean non lorem sit amet purus placerat porta id nec urna. Curabitur vitae lorem mi.",ingredients:"4 ous,150 g farina,180 g de sucre panela,50 g  de mantega,40 g oli de gira-sol,5 g de llevat,2  pomes Golden,2 pomes Granny Smith,2 cullerades de canyella en pols,2 canonets de canyella,cava,sal"}
                                    ];

